language: java
addons:
  sonarcloud:
    organization: nmhill-github
    token:
      secure: SONAR_TOKEN
jdk:
  - oraclejdk10
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar